name: cogvideo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.5.0
  - pytorch-cuda=12.1
  - torchvision>=0.20.0
  - cuda-toolkit
  - pip
  - ipdb
  - pip:
    - accelerate>=1.1.1
    - transformers>=4.46.2
    - numpy==1.26.0
    - sentencepiece>=0.2.0
    - SwissArmyTransformer>=0.4.12
    - gradio>=5.5.0
    - imageio>=2.35.1
    - imageio-ffmpeg>=0.5.1
    - openai>=1.54.0
    - moviepy>=2.0.0
    - scikit-video>=1.1.11
    - pydantic>=2.10.3
    - peft
    - opencv-python
    - matplotlib
    - ipykernel
    - wandb
    - decord
    - einops
    - tifffile
    - pandas
    - ipykernel
    - h5py